# Generated by Django 5.0.6 on 2024-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
