# Generated by Django 5.0.6 on 2024-09-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='AvailableTime',
            new_name='availableTime',
        ),
    ]
