# Generated by Django 5.0.6 on 2024-09-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_availabletime_doctor_availabletime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='availableTime',
            new_name='available_time',
        ),
    ]
